### ISSUE TITLE
[feature] Support for blog posts

### ISSUE THREAD

**Issue by abtris** [koostudios/kel#2]
- as jekyll will be nice some post folder and make simple blog with posts

**Comment by koostudios** [comment]
Thanks @abtris for your interest and your contribution. I will be looking toward bringing some kind of simple blog system but I am not sure how to implement it yet as simply as possible. I want to take this opportunity to note that Kel is not a static site generator like Jekyll nor does it aim to be. However, I do agree that blog posts would be amazing with Kel.
